export const CHAT_ACTION_TYPE = {
    SET_ACTIVE_CONVERSATION: 'SET_ACTIVE_CONVERSATION',
    FETCH_CONVERSATION_START: 'FETCH_CONVERSATION_START',
    FETCH_CONVERSATION_SUCCESS: 'FETCH_CONVERSATION_SUCCESS',
    FETCH_CONVERSATION_FAILED: 'FETCH_CONVERSATION_FAILED',
    FETCH_ACTIVE_CONVERSATION_START: 'FETCH_ACTIVE_CONVERSATION_START',
    FETCH_ACTIVE_CONVERSATION_SUCCESS: 'FETCH_ACTIVE_CONVERSATION_SUCCESS',
    FETCH_ACTIVE_CONVERSATION_FAILED: 'FETCH_ACTIVE_CONVERSATION_FAILED',
    FETCH_MESSAGES_START: 'FETCH_MESSAGES_START',
    FETCH_MESSAGES_SUCCESS: 'FETCH_MESSAGES_SUCCESS',
    FETCH_MESSAGES_FAILED: 'FETCH_MESSAGES_FAILED',
    SEND_MESSAGE_START: 'SEND_MESSAGE_START',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILED: 'SEND_MESSAGE_FAILED',
    HANDLE_MESSAGE_RECEIVED: 'HANDLE_MESSAGE_RECEIVED',
    SET_ONLINE_USERS: 'SET_ONLINE_USERS',
    CLEAR_CHAT_STATE: 'CLEAR_CHAT_STATE'
}