export const CHAT_ACTION_TYPE = {
    SET_ACTIVE_CONVERSATION: 'SET_ACTIVE_CONVERSATION',
    FETCH_CONVERSATION_START: 'FETCH_CONVERSATION_START',
    FETCH_CONVERSATION_SUCCESS: 'FETCH_CONVERSATION_SUCCESS',
    FETCH_CONVERSATION_FAILED: 'FETCH_CONVERSATION_FAILED',
    FETCH_ACTIVE_CONVERSATION_START: 'FETCH_ACTIVE_CONVERSATION_START',
    FETCH_ACTIVE_CONVERSATION_SUCCESS: 'FETCH_ACTIVE_CONVERSATION_SUCCESS',
    FETCH_ACTIVE_CONVERSATION_FAILED: 'FETCH_ACTIVE_CONVERSATION_FAILED',
}