export const USER_ACTION_TYPE = {
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILED: 'FETCH_USER_FAILED',
    LOGIN_USER_START: 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
    LOGOUT_USER: 'LOGOUT_USER',
    UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
    UPDATE_STATUS_START: 'UPDATE_STATUS_START',
    UPDATE_STATUT_SUCCESS: 'UPDATE_STATUS_SUCCESS',
    UPDATE_STATUS_FAILED: 'UPDATE_STATUS_FAILED'
}